"""create job_preferences table

Revision ID: 9a33a3c48fe4
Revises: 18ea59406911
Create Date: 2026-07-07 16:33:33.043338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a33a3c48fe4'
down_revision: Union[str, Sequence[str], None] = '18ea59406911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_roles', sa.String(length=255), nullable=False),
    sa.Column('preferred_locations', sa.String(length=255), nullable=True),
    sa.Column('preferred_industries', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('expected_salary_lpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_job_preferences_id'), 'job_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_preferences_id'), table_name='job_preferences')
    op.drop_table('job_preferences')
    # ### end Alembic commands ###
